version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Serverless...
      - yarn global add serverless
      - echo Installing Serverless...
      - yarn global add aws-cli
  pre_build:
    commands:
      - yarn
      - yarn build
  build:
    commands:
      - echo Deploying with Serverless Framework
      - sls deploy -v -s dev
      - sls syncToS3
  post_build:
    commands:
      - echo Deployment completed on `date`